### ISSUE TITLE
Hi what is the name of template of the backend do you us ?

### ISSUE THREAD

**Issue by issour** [tanthammar/tall-data-table#1]
![C481D8C4-56C0-44F7-9992-8B8404984816](https://user-images.githubusercontent.com/44650070/87245203-0edd9400-c433-11ea-9318-0488afd3aff0.jpeg)
Thx

**Comment by tanthammar** [comment]
It is based on the TailwindUI "Dark sidebar with light header" component.
https://tailwindui.com/components/application-ui/application-shells/sidebar#component-9899e7dd65f66e9a3ee78e7bb1abdeaa

**Comment by issour** [comment]
Thanks you !!!
